import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'
import Nav from './components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Toyota - 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="relative flex w-full flex-col items-center">
          <div className="w-[90%]">
            <Nav />
          </div>
          {children}
          <Image
            src="/assets/images/bg-decoration.png"
            alt="Toyota Logo"
            width={785}
            height={165}
            className="absolute left-0 top-0 -z-20 opacity-60"
          />
        </div>
      </body>
    </html>
  )
}
